services:
  capacitor:
    image: vesaber/capacitor:latest
    env_file: .env
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - "989"
    restart: unless-stopped
